<?php

namespace AppBundle\Repository;

/**
 * ThreadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByCreatedAt($board)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT t FROM AppBundle:Thread t WHERE t.board = :board ORDER BY t.createdAt DESC'
            )->setParameter('board', $board)
            ->getResult();
    }
}
